# -*- coding: utf-8 -*-
"""rag_chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nyGMNTMuWpx3ktHMy6rW38f7prlYNoTE
"""

import os
from langchain_experimental.text_splitter import SemanticChunker
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_community.vectorstores import FAISS
from langchain_core.documents import Document


# 1. Initialize Shared Embedding Model

# We load this once and use it for both chunking and searching.
print("Loading embedding model...")
embeddings = HuggingFaceEmbeddings(model_name="all-MiniLM-L6-v2")


# 2. Setup Semantic Chunker

# breakpoint_threshold_type="percentile" is great for policy docs.
text_splitter = SemanticChunker(
    embeddings,
    breakpoint_threshold_type="percentile"
)


# 3. Process the Document
file_path = "upwork.txt"

if not os.path.exists(file_path):
    print(f"Error: {file_path} not found. Please ensure the file exists.")
    exit()

with open(file_path, "r", encoding="utf-8") as f:
    raw_text = f.read()

print("Creating semantic chunks (this may take a moment)...")
docs = text_splitter.create_documents([raw_text])
print(f"Total semantic chunks created: {len(docs)}")


# 4. Create Vector Store (FAISS)

# This indexes your chunks so they can be searched instantly.
print("Indexing chunks into Vector Store...")
vector_db = FAISS.from_documents(docs, embeddings)

# 5. Retrieval & Answering Logic

def answer_question(question, score_threshold=0.4):
    """
    Finds relevant context.
    similarity_search_with_relevance_scores returns a tuple: (Document, Score)
    Note: Scores closer to 1.0 are more relevant.
    """
    results = vector_db.similarity_search_with_relevance_scores(question, k=3)

    # Filter results based on confidence threshold
    valid_chunks = [doc.page_content for doc, score in results if score >= score_threshold]

    if not valid_chunks:
        return "I'm sorry, I couldn't find any relevant information in the Upwork guide for that question."

    # Join the relevant sections found
    context_text = "\n\n--- Relevant Section ---\n\n".join(valid_chunks)
    return context_text


# 6. Chat Loop

print("\n" + "="*30)
print("UPWORK POLICY ASSISTANT READY")
print("Type 'exit' to quit.")
print("="*30 + "\n")

while True:
    user_input = input("User: ").strip()

    if user_input.lower() in ["exit", "quit"]:
        print("Goodbye!")
        break

    if not user_input:
        continue

    response = answer_question(user_input)

    print("\nAssistant (Found Context):")
    print(response)
    print("\n" + "-"*50 + "\n")